myapp/urls.py
from django.urls import path 
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('update-todo/<int:pk>', views.update_todo, name='update-todo'),
    path('delete-todo/<int:pk>', views.delete_todo, name='delete-todo'),
    path('delete-task/<int:pk>', views.DeleteTask.as_view(), name='delete-task'),
    path('tasklist/', views.AllTask.as_view(), name='task-list'),
    path('view-task/<int:pk>', views.task_detail, name='task-detail'),
    path('update-task/<int:pk>', views.update_task, name='task-update'),
    path('new-task/', views.create_task, name='new-task'),
    path('whats-this-day/', views.on_day, name="whats-this-day"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/models.py
from django.db import models
from django.urls import reverse 

class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()

    created_at = models.DateField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("myapp:home")
    
    def __str__(self):
        return self.title 


class ToDo(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    date = models.DateField()

    is_completed = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.task.title} is to be done at {self.date} and Completed:{self.is_completed}"

myapp/views.py
from django.contrib import messages
from django.urls import reverse, reverse_lazy 
from django.http import HttpResponseNotAllowed, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, DetailView, ListView
from .models import Task, ToDo 
from datetime import date, datetime, timedelta

def home(request):
    today = date.today()
    yestarday = today - timedelta(days=1)
    tomorrow = today + timedelta(days=1)
    todo_list = ToDo.objects.filter(date=date.today())
    yestarday_todo_list = ToDo.objects.filter(date=yestarday, is_completed=False)
    tomorrow_todo_list = ToDo.objects.filter(date=tomorrow)
    return render(request, 'myapp/todo_list.html', context={'todo_list': todo_list, 'yestarday_todo_list': yestarday_todo_list, 'tomorrow_todo_list': tomorrow_todo_list })

def update_todo(request, pk):
    if request.method == 'POST':
        todo = get_object_or_404(ToDo, pk=pk)
        todo.is_completed = not todo.is_completed
        todo.save()
        return JsonResponse({"status":f"{todo.is_completed}"})
    else:
        return HttpResponseNotAllowed('Not allowed')

def create_task(request):
    if request.method == 'GET':
        return render(request, 'myapp/task_form.html')
    else:
        date_list_string = request.POST.get('date-list-string')
        title = request.POST.get('title')
        description = request.POST.get('description')
        date_list = date_list_string.split(',')[:-1]
        task = Task.objects.create(title=title, description=description)
        for d in date_list:
            d, m, y = list(map(int, d.split('-')))
            todo = ToDo.objects.get_or_create(task=task, date=datetime(y, m+1, d))

        return redirect(reverse('myapp:task-detail', args=[task.pk]))

class DeleteTask(DeleteView):
    model = Task 
    success_url = reverse_lazy('myapp:home')

class AllTask(ListView):
    model = Task 
    def get_queryset(self):
        return Task.objects.all().order_by('-created_at')

def task_detail(request, pk):
    task = get_object_or_404(Task, pk=pk)
    todo_list = ToDo.objects.filter(task=task).order_by('date')
    return render(request, 'myapp/task_detail.html', context={'task': task, 'todo_list': todo_list})

def update_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    todos = ToDo.objects.filter(task=task)
    date_list_string = ''
    if request.method == 'GET':
        for todo in todos:
            d = int(todo.date.strftime('%d'))
            m = int(todo.date.strftime('%m'))-1
            y = todo.date.strftime('%Y')
            date_list_string = date_list_string + f"{d}-{m}-{y},"
        return render(request, 'myapp/task_form.html', context={'form': {'title': task.title, 'pk': task.pk, 'date_list_string': date_list_string, 'description': task.description}})
    else:
        date_list_string = request.POST.get('date-list-string')
        title = request.POST.get('title')
        description = request.POST.get('description')
        new_date_list = date_list_string.split(',')[:-1]
        task.title = title 
        task.description = description
        task.save()
        for d in new_date_list:
            d, m, y = list(map(int, d.split('-')))
            todo = ToDo.objects.filter(task=task, date=datetime(y, m+1, d))
            if not todo:
                ToDo.objects.create(task=task, date=datetime(y, m+1, d))
        messages.success(request, 'Task Update Successfully!')
        return redirect(reverse('myapp:task-detail', args=[task.pk]))
    

def delete_todo(request, pk):
    if request.method == 'POST':
        todo = get_object_or_404(ToDo, pk=pk)
        todo.delete()
        return JsonResponse({"status": "deleted"})
    else:
        return HttpResponseNotAllowed("Not Allowed")

def on_day(request):
    d = request.GET.get('date')
    print(d)
    todo_list = ToDo.objects.filter(date=datetime.strptime(d, '%Y-%m-%d'))
    return render(request, 'myapp/on_date.html', context={'todo_list': todo_list, 'date': d})

myapp/templates/myapp/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- <meta http-equiv="refresh" content="2"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicons -->
    <link rel="icon" type="image/png" sizes="32x32" href="https://i.ibb.co/bBTLN1b/revisiondiary-16x16.png">
    <link rel="icon" type="image/png" sizes="96x96" href="https://i.ibb.co/TBx3mwB/revisiondiary-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://i.ibb.co/2g6LCPw/revisiondiary-favicon-96x96.png">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Fontawesome Icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- TinyMCE -->
    <script src="https://cdn.tiny.cloud/1/7k6426m3rgtuf42vntbpffxgc683s0tlhsiza37pvkrtn81w/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <title>{% block page_title %}{% endblock page_title %}</title>

    {% block page_links_top %}{% endblock page_links_top %}
    {% block page_styles %}{% endblock page_styles %}
    {% block page_scripts_top %}{% endblock page_scripts_top %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'myapp:home' %}">Revision Diary</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-navbarSupportedContent" aria-controls="main-navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="main-navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:task-list' %}">All Tasks</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:new-task' %}">New Task</a>
            </li>
            <!--<li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>-->
          </ul>
          <form class="d-flex" method="GET" action="{% url 'myapp:whats-this-day' %}">
            <input class="form-control me-2" type="date" name="date" required>
            <button class="btn btn-outline-success" type="submit">Go</button>
          </form>
        </div>
      </div>
    </nav>
    {% if messages %}
    <div class="container my-1">
      {% for message in messages %}
      <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
        <strong>{{message.tags}}</strong>{{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    </div>
    {% endif %}
    {% block page_content %}{% endblock page_content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Axios Links-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
    <script>
        function update(url, dataList, onSuccess, onFail, onSuccessArgs, onFailArgs){
            let data = new FormData();
            dataList.forEach(dataItem => {
                data.append(dataItem[0], dataItem[1])
            })
            // data.append("csrfmiddlewaretoken", '{{csrf_token}}')

            axios.post(url, data)
            .then(res => onSuccess(res, onSuccessArgs))
            .catch(errors => onFail(errors, onFailArgs))
        }
    </script>
    <script>
      // paste function
      async function paste(input) {
        const text = await navigator.clipboard.readText();
        input.value = text;
      }
      // copy function
      function copy(text) {
        navigator.clipboard.writeText(text);
      }
    </script>
    {% block page_links_bottom %}{% endblock page_links_bottom %}
    {% block page_scripts_bottom %}{% endblock page_scripts_bottom %}
  </body>
</html>

myapp/templates/myapp/on_date.html
{% extends 'myapp/base.html' %}
{% block page_title %}{{date}} {% endblock page_title %}
{% block page_links_top %}{% endblock page_links_top %}
{% block page_styles %}
<style>
    .y-todo{
        cursor: pointer;
    }
    .check-icon{
        cursor: pointer;
    }
</style>
{% endblock page_styles %}
{% block page_scripts_top %}{% endblock page_scripts_top %}
{% block nav_links %}{% endblock nav_links %}


{% block page_content %}
    <div class="container mt-3 mb-5">
        <h2>{{date}}</h2>
        {% for todo in todo_list %}
        <p class="lead fs-4">
            <i data-pk="{{todo.pk}}" class="mx-1 check-icon fa {% if todo.is_completed %}fa-check-square text-success {% else %} fa-square text-danger{% endif %}" aria-hidden="true"></i>
            <a class="text-decoration-none" href="{% url 'myapp:task-detail' todo.task.pk %}">{{todo.task.title}}</a>
        </p>
        {% endfor %}
    </div>
{% endblock page_content %}


{% block page_links_bottom %}{% endblock page_links_bottom %}
{% block page_scripts_bottom %}
<script>
    let yTodos = document.querySelectorAll('.y-todo')
    yTodos.forEach(todo => {
        let pk = todo.dataset.pk 
        todo.addEventListener('click', todo=>{
            update(`/delete-todo/${pk}` ,
                [['csrfmiddlewaretoken', '{{csrf_token}}'], ['date', date]], 
                ()=>{
                    alert('Deleted')
                    window.location.reload();
                }, 
                ()=>alert('Error'), 
                null, 
                null
                )
        })
    })
    let checkIcons = document.querySelectorAll('.check-icon')
    checkIcons.forEach(icon => {
        let pk = icon.dataset.pk 
        icon.addEventListener('click', ()=>{
            update(`/update-todo/${pk}`, 
                    [['csrfmiddlewaretoken', '{{csrf_token}}']], 
                    ()=>{
                        alert('Congratulations! Done')
                        window.location.reload()
                    },
                    ()=> alert('Error'),
                    null,
                    null
            )
        })
    })
</script>
{% endblock page_scripts_bottom %}

myapp/templates/myapp/task_confirm_delete.html
{% extends 'myapp/base.html' %}
{% block page_title %}Confirm Delete {{task.title}}{% endblock page_title %}
{% block page_links_top %}{% endblock page_links_top %}
{% block page_styles %}{% endblock page_styles %}
{% block page_scripts_top %}{% endblock page_scripts_top %}
{% block nav_links %}{% endblock nav_links %}
{% block page_content %}

<div class="container mt-3 mb-5">
    <div class="w-50 m-auto">
        <h3>Confirm Delete {{task.title}}?</h3>
        <form method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Confirm Delete" class="btn btn-danger">
            <a href="{% url 'myapp:task-detail' task.pk %}">Cancel</a>
        </form>
    </div>
</div>

{% endblock page_content %}
{% block page_links_bottom %}{% endblock page_links_bottom %}
{% block page_scripts_bottom %}{% endblock page_scripts_bottom %}

myapp/templates/myapp/task_detail.html
{% extends 'myapp/base.html' %}
{% block page_title %}{{task.title}}{% endblock page_title %}
{% block page_links_top %}{% endblock page_links_top %}
{% block page_styles %}{% endblock page_styles %}
{% block page_scripts_top %}{% endblock page_scripts_top %}
{% block nav_links %}{% endblock nav_links %}


{% block page_content %}
<div class="container mt-3 mb-5">
    <h3 class="d-flex flex-row justify-content-between align-items-center">
        <div class="col-11">
            {{task.title}}
        </div>
        <div class="col-1 d-flex justify-content-between">
            <a href="{% url 'myapp:task-update' task.pk %}" class="text-decoration-none"><i class="fa fa-pencil" aria-hidden="true"></i></a>
            <a href="{% url 'myapp:delete-task' task.pk %}" class="text-decoration-none"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
        </div>
    </h3>
    <hr>
    <p>{{task.description|safe}}</p>
    <hr>
    {% for todo in todo_list %}
        {{todo.date}} {% if todo.is_completed %} <i class="fa fa-check-circle text-success" aria-hidden="true"></i>{% else %} {% endif %}<br>
    {% endfor %}
</div>

{% endblock page_content %}


{% block page_links_bottom %}{% endblock page_links_bottom %}
{% block page_scripts_bottom %}{% endblock page_scripts_bottom %}

myapp/templates/myapp/task_form.html
{% extends 'myapp/base.html' %}
{% block page_title %}Create A New Task{% endblock page_title %}
{% block page_links_top %}{% endblock page_links_top %}
{% block page_styles %}
<style>
    .date{
        width: 60px;
        height: 60px;
        display: flex;
        justify-content: center;
        align-items: center;
        border-collapse: collapse;
    }
    .calender-div{
        width: 420px;
        height: 490px;
    }
</style>
{% endblock page_styles %}
{% block page_scripts_top %}{% endblock page_scripts_top %}
{% block nav_links %}{% endblock nav_links %}


{% block page_content %}
<div class="container mt-3 mb-5">
    <form method="POST" class="m-auto mt-2 shadow p-3 w-75 rounded-top">
        {% csrf_token %}
        {% if form.pk %}
        <input type="text" name="pk" id="pk" class="form-control" hidden value="{{form.pk}}">
        {% endif %}
        {% if form.pk %}
        <h5>Update {{form.title}}</h5>
        {% else %}
        <h5>Add New Task</h5>
        {% endif %}
        <div class="mb-3">
            <label for="title" class="form-label">Enter Task Title</label>
            {% if form.pk %}
            <input type="text" name="title" id="title" class="form-control" placeholder="Enter Task Title" value="{{form.title}}">
            {% else %}
            <input type="text" name="title" id="title" class="form-control" placeholder="Enter Task Title">
            {% endif %}
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Enter Description</label>
            {% if form.pk %}
            <textarea name="description" id="description" cols="30" rows="3" class="form-control">{{form.description}}</textarea>
            {% else %}
            <textarea name="description" id="description" cols="30" rows="3" class="form-control"></textarea>
            {% endif %}
        </div>
        <div class="mb-3">
            <label for="date-list-string" class="form-label">Dates</label>
            {% if form.pk %}
            <input type="text" name="date-list-string" id="date-list-string" class="form-control" readonly value="{{form.date_list_string}}">
            {% else %}
            <input type="text" name="date-list-string" id="date-list-string" class="form-control" readonly>
            {% endif %}
        </div>
        <div class="calender-div m-auto bg-light">
            <div class="header d-flex justify-content-between align-items-center w-100 border">
                <div class="goto-prev"><button class=" btn btn-primary btn-sm" id="prev-month"><i class="fa fa-chevron-left" aria-hidden="true"></i>&nbsp;Prev</button></div>
                <div id="month-name">Feb 2022</div>
                <div class="goto-next"><button class=" btn btn-primary btn-sm" id="next-month">Next&nbsp;<i class="fa fa-chevron-right" aria-hidden="true"></i></button></div>
            </div>
            <div class="dates w-100">
                <div class="days">
                    <div class="d-flex flex-row">
                        <div class="date border">Mon</div>
                        <div class="date border">Tue</div>
                        <div class="date border">Wed</div>
                        <div class="date border">Thu</div>
                        <div class="date border">Fri</div>
                        <div class="date border">Sat</div>
                        <div class="date border">Sun</div>
                    </div>
                </div>
                <div id="actual-dates" class=" d-flex flex-row flex-wrap"></div>
            </div>
        </div>


        <input type="submit" value="Save" class="btn btn-primary m-auto d-block mt-3">
    </form>
</div>
{% endblock page_content %}


{% block page_links_bottom %}{% endblock page_links_bottom %}
{% block page_scripts_bottom %}
<script>
    tinymce.init({
    selector: 'textarea',
    plugins: 'print preview powerpaste casechange  autolink directionality advcode visualblocks visualchars image link media mediaembed table charmap nonbreaking anchor toc insertdatetime advlist lists checklist wordcount tinymcespellchecker  imagetools textpattern charmap  mentions quickbars linkchecker emoticons advtable export',
    menubar: false,
    toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor backcolor charmap emoticons image link',
    quickbars_selection_toolbar: 'bold italic | quicklink h2 h3 blockquote quickimage quicktable',
    });
    let form = document.querySelector('form')
    form.addEventListener('submit', event=>{
        event.preventDefault()
        let textarea = document.querySelector('textarea')
        textarea.value = tinymce.get('textarea').getContent();
        form.submit()
    })
</script>
<script>
    var today = new Date();
    var m = today.getMonth()
    var y = today.getFullYear()
    var m_dict = {'0': 'Jan','1': 'Feb','2': 'Mar','3': 'Apr','4': 'May','5': 'Jun','6': 'Jul','7': 'Aug','8': 'Sep','9': 'Oct','10': 'Nov','11': 'Dec'}
    var active_m_name = m_dict[m]
    var active_m = m
    var active_y = y 
    var selected_dates = []
    function checkLeapYear(year) {
        if ((0 == year % 4) && (0 != year % 100) || (0 == year % 400)) {
            return true 
        } else {
            return false
        }
    }

    function next(m, y){
        var n_m = (m + 1) % 12
        var n_y = m==11 ? y + 1 : y 
        active_m = n_m
        active_y = n_y
        active_m_name = m_dict[active_m]
    }
    function prev(m, y){
        var p_m = m==0 ? 11 : m - 1 
        var p_y = m==0 ? y - 1 : y 
        active_m = p_m 
        active_y = p_y 
        active_m_name = m_dict[active_m]
    }
    function getNoOfDays(m, y){
        if(checkLeapYear(y) && m==1)
            return 29
        if(!checkLeapYear(y) && m==1)
            return 28
        var days = {
            '0': '31',
            '2': '31',
            '3': '30',
            '4': '31',
            '5': '30',
            '6': '31',
            '7': '31',
            '8': '30',
            '9': '31',
            '10': '30',
            '11': '31'
        }
        return +days[m]
    }
    
    let prevBtn = document.querySelector('#prev-month')
    let nextBtn = document.querySelector('#next-month')
    function populate(){
        let totalDays = getNoOfDays(active_m, active_y)
        let first_date = new Date(active_y, active_m, 1)
        let last_date = new Date(active_y, active_m, totalDays)
        let pre_blanks = first_date.getDay() - 1 
        // let post_blanks = 7 - last_date.getDay()
        // if(post_blanks==7)
        post_blanks = 0
        let dates_list = []
        for(let i =0;i<(+pre_blanks);i++) 
            dates_list.push(0)
        for(let i =1;i<=totalDays;i++) 
            dates_list.push(i)
        for(let i =0;i<(+post_blanks);i++) 
            dates_list.push(0)
        
        let actualDates = document.querySelector('#actual-dates')
        let monthName = document.querySelector('#month-name')
        monthName.innerHTML = `${active_m_name} ${active_y}`
        actualDates.innerHTML = ''
        dates_list.forEach(date => {
            let classList = ''
            if(selected_dates.includes(`${date}-${active_m}-${active_y}`)){
                classList = 'btn btn-primary'
            } else {
                classList = 'btn btn-outline-primary'
            }
            if(date==0){
                actualDates.innerHTML = actualDates.innerHTML + 
                `<div class="date border"></div>`
            } else if(1<=date && date<=9){
                actualDates.innerHTML = actualDates.innerHTML + 
                `<div class="date border"><button role="button" id="date-${date}-${active_m}-${active_y}" data-date="${date}" data-month="${active_m}" data-year="${active_y}" onclick="toggleSelect(event)" class="${classList}">&nbsp;${date}</button></div>`
            } else{
                actualDates.innerHTML = actualDates.innerHTML + 
                `<div class="date border"><button role="button" id="date-${date}-${active_m}-${active_y}" data-date="${date}" data-month="${active_m}" data-year="${active_y}" onclick="toggleSelect(event)" class="${classList}">${date}</button></div>`
            }
            
        })
    }
    prevBtn.addEventListener('click', (e)=>{
        e.preventDefault()
        prev(active_m, active_y)
        populate()
    })
    nextBtn.addEventListener('click', (e)=>{
        e.preventDefault()
        next(active_m, active_y)
        populate()
    })
    
    function select(date){
        console.log(date)
        let btn = document.querySelector(`#date-${date}`)
        btn.classList.remove('btn-outline-primary')
        btn.classList.add('btn-primary')
        btn.blur()
        selected_dates.push(date)
    }
    function unselect(date){
        console.log(date)
        let btn = document.querySelector(`#date-${date}`)
        btn.classList.add('btn-outline-primary')
        btn.classList.remove('btn-primary')
        btn.blur()
        let index = selected_dates.indexOf(date)
        if(index > -1){
            selected_dates.splice(index, 1)
        }
    }
    function toggleSelect(event){
        event.preventDefault()
        let d = event.target.dataset.date 
        let m = event.target.dataset.month 
        let y = event.target.dataset.year 
        let date = `${d}-${m}-${y}`
        if(selected_dates.includes(date)){
            unselect(date)
        }else {
            select(date) 
        }
        let input = document.querySelector('#date-list-string')
        input.value = ''
        selected_dates.forEach(date=>{
            input.value = input.value +
            `${date},`
        })
    }
</script>

    {% if form.pk %}
    <script>
        window.onload = ()=> {
            let str = '{{form.date_list_string}}'
            let list = str.split(',').slice(0, -1)
            list.forEach(item=>{
                selected_dates.push(item)
            })
            populate()
            console.log(selected_dates)
        }
    </script>
    {% else %}
    <script>
        window.onload = ()=> {
            populate()
        }
    </script>
    {% endif %}
{% endblock page_scripts_bottom %}

myapp/templates/myapp/task_list.html
{% extends 'myapp/base.html' %}
{% block page_title %}All Tasks{% endblock page_title %}
{% block page_links_top %}{% endblock page_links_top %}
{% block page_styles %}{% endblock page_styles %}
{% block page_scripts_top %}{% endblock page_scripts_top %}
{% block nav_links %}{% endblock nav_links %}
{% block page_content %}
<div class="container mt-3 mb-5">
    {% for task in task_list %}
    <p><a href="{% url 'myapp:task-detail' task.pk %}">{{task.title}}</a></p>
    {% endfor %}
</div>
{% endblock page_content %}
{% block page_links_bottom %}{% endblock page_links_bottom %}
{% block page_scripts_bottom %}{% endblock page_scripts_bottom %}